sudo: false
language: node_js
node_js:
  - 'node'
  - '8'
install: npm install
addons:
  apt:
    sources:
    - sourceline: 'deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
    packages:
    - mongodb-org-server
before_script:
  - mkdir db/
  - mongod --dbpath db/ &
